name: Industrial CI
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - humble

jobs:
  industrial_ci:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone installation requirements
        shell: bash
        run : python3 -m pip install -U vcstool &&
              vcs import . < ./rosbot/rosbot_hardware.repos &&
              vcs import . < ./rosbot/rosbot_simulation.repos
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{matrix.ROS_DISTRO}}
