name: CI
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  
jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        ROS_REPO: [humble]
        ROS_DISTRO: [humble]
    runs-on: ubuntu-latest
    steps:
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: ${{matrix.ROS_REPO}}
          ROS_DISTRO: ${{matrix.ROS_DISTRO}}
